# Codecov configuration

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 60%
        threshold: 10%

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "examples/**/*"
  - "scripts/**/*"
  - "**/__pycache__/**/*"
