# Codecov configuration for QuantumFold-Advantage
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "docs/**/*"
  - "setup.py"
  - "**/test_*.py"
  - "**/__pycache__/**/*"

flags:
  unittests:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - src/
    carryforward: true

github_checks:
  annotations: true
