"""Visualization utilities for protein structures."""

import logging

import numpy as np

logger = logging.getLogger(__name__)


def visualize_protein_structure(coords, sequence, output_path="structure.pdb"):
    """
    Generate PDB file for protein structure visualization.

    Args:
        coords: (N, 3) array of 3D coordinates
        sequence: Amino acid sequence string
        output_path: Output PDB file path
    """
    logger.info(f"Writing PDB structure to {output_path}")

    with open(output_path, "w") as f:
        f.write("HEADER    QUANTUMFOLD-ADVANTAGE PREDICTION\n")
        f.write("TITLE     HYBRID QUANTUM-CLASSICAL PROTEIN FOLDING\n")
        f.write("REMARK    Generated by QuantumFold-Advantage\n")

        for i, (coord, aa) in enumerate(zip(coords, sequence), start=1):
            x, y, z = coord
            # PDB ATOM format:
            # ATOM      1  CA  ALA A   1      10.000  20.000  30.000  1.00  0.00           C
            line = (
                f"ATOM  {i:5d}  CA  {aa:3s} A{i:4d}    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           C\n"
            )
            f.write(line)

        f.write("END\n")

    logger.info(f"PDB file written with {len(coords)} atoms")


def plot_training_curves(history, output_path="training_curves.png"):
    """
    Plot training and validation loss curves.

    Args:
        history: Dictionary with 'train_loss' and 'val_loss' lists
        output_path: Output image path
    """
    try:
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.plot(history["train_loss"], label="Train Loss", marker="o")
        ax.plot(history["val_loss"], label="Val Loss", marker="s")
        ax.set_xlabel("Epoch")
        ax.set_ylabel("Loss")
        ax.set_title("Training History")
        ax.legend()
        ax.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.savefig(output_path, dpi=300, bbox_inches="tight")
        plt.close()

        logger.info(f"Training curves saved to {output_path}")
    except ImportError:
        logger.warning("matplotlib not available, skipping plot generation")
